name: visionspark
description: "A Flutter application for generating AI images using DALL-E 3."
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  loading_animation_widget: ^1.2.0+4
  supabase_flutter: ^2.5.0
  sign_in_with_apple: ^7.0.1
  flutter_timezone: ^4.1.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  app_links: ^3.0.0
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.2
  in_app_purchase: ^3.2.3
  image: ^4.1.7
  google_sign_in: ^6.2.1
  flutter_staggered_grid_view: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
