-- supabase/migrations/20240607_0_create_gallery_images_table.sql

-- Create the public.gallery_images table
CREATE TABLE public.gallery_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  image_path TEXT NOT NULL, -- Path to the image in Supabase Storage
  prompt TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- Add comments to the table and columns
COMMENT ON TABLE public.gallery_images IS 'Stores images generated by users and shared to the gallery.';
COMMENT ON COLUMN public.gallery_images.id IS 'Unique identifier for the gallery image.';
COMMENT ON COLUMN public.gallery_images.user_id IS 'Owner of the image, references auth.users.id.';
COMMENT ON COLUMN public.gallery_images.image_path IS 'Path to the full-resolution image in Supabase Storage.';
COMMENT ON COLUMN public.gallery_images.prompt IS 'The prompt used to generate the image.';
COMMENT ON COLUMN public.gallery_images.created_at IS 'Timestamp of when the gallery image was created.';

-- Enable RLS for the gallery_images table
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;

-- RLS Policies for gallery_images

-- POLICY: Allow authenticated users to INSERT new gallery images
CREATE POLICY "Authenticated users can insert gallery images"
ON public.gallery_images
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- POLICY: Allow public read access to gallery images
CREATE POLICY "Allow public read access to gallery images"
ON public.gallery_images
FOR SELECT
USING (true); -- Or TO public; or TO authenticated; depending on desired visibility. For a public gallery, true is common.

-- POLICY: Allow users to UPDATE their own gallery images (e.g., prompt)
CREATE POLICY "Users can update their own gallery images"
ON public.gallery_images
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id); -- Ensures they can only update their own.

-- POLICY: Allow users to DELETE their own gallery images
CREATE POLICY "Users can delete their own gallery images"
ON public.gallery_images
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
